[package]
name = "chrono-net-ex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { path = "../chrono/chrono"}
heapless = {version = "0.7.10", features = ["default", "defmt-impl"] }

panic-probe = { version = "0.3.0", features = ["print-defmt"] }
cortex-m = "0.7.4"
cortex-m-rt = "0.7.1"
defmt-rtt = "0.3.2"
stm32f3 = { version = "0.14.0", features = ["stm32f303", "rt"] }
defmt = "0.3.1"
enc28j60 = { git = "https://github.com/senyosimpson/enc28j60", branch = "master" }
smoltcp = { version = "0.8.1", default-features = false, features = [
    "defmt",
    "medium-ethernet",
    "medium-ip",
    "proto-ipv4",
    "proto-ipv6",
    "socket-tcp",
    "socket-icmp",
] }

[profile.release]
debug = 2