[package]
name = "chrono"
version = "0.1.0"
authors = ["SenYeezus <simpsonsenyo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.97"
bitflags = "1.2.1"
crossbeam = "0.8.1"
slab = "0.4.3"
futures = "0.3.15"
tracing = "0.1.29"
once_cell = "1.10.0"
heapless = "0.7.10"

chrono-macros = { path = "../chrono-macros"}