[package]
name = "tcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
chrono = { path = "../../chrono", features = ["networking"]}
panic-probe = { version = "0.3.0", features = ["print-defmt"] }
cortex-m = "0.7.4"
cortex-m-rt = "0.7.1"
defmt-rtt = "0.3.2"
stm32f3 = { version = "0.14.0", features = ["stm32f303", "rt"] }
defmt = "0.3.1"


[profile.release]
debug = 2